# Generated by Django 2.2.7 on 2020-03-29 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Email',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now=True, verbose_name='Дата создания')),
                ('date_send', models.DateTimeField(null=True, verbose_name='Дата отправки')),
                ('interval', models.PositiveIntegerField(verbose_name='Количество секунд')),
                ('subject', models.CharField(max_length=150, verbose_name='Тема письма')),
                ('message', models.CharField(max_length=500, verbose_name='Сообщение')),
                ('send_to', models.EmailField(max_length=254, verbose_name='Получатель')),
            ],
            options={
                'verbose_name': 'Письмо',
                'verbose_name_plural': 'Письма',
            },
        ),
    ]
