# Generated by Django 2.2.7 on 2020-03-29 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sender', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='email',
            name='date_send',
        ),
        migrations.AlterField(
            model_name='email',
            name='date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата создания'),
        ),
    ]
